services:
  dev:
    build: .
    container_name: cpp_qt_dev
    ports:
      - "8080:8080"
    volumes:
      - ${DOCKER_COPY_FILES_DIR}/.docker_gitconfig:/home/devuser/.gitconfig
      - ${DOCKER_COPY_FILES_DIR}/.docker_ssh_key:/home/devuser/.ssh/id_ed25519
      - ${DOCKER_COPY_FILES_DIR}/.docker_ssh_key.pub:/home/devuser/.ssh/id_ed25519.pub
      - ${DOCKER_COPY_FILES_DIR}/ReceiptReader/setup-container.sh:/home/devuser/setup-container.sh
      - ${DOCKER_COPY_FILES_DIR}/Pictures/Receipts:/home/devuser/Pictures/Receipts
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    stdin_open: true
    tty: true
